
/*
 * 
 */

package es.caib.digital.ws.api.copiaautentica;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.12-patch-04
 * Wed Mar 09 13:26:15 CET 2016
 * Generated source version: 2.2.12-patch-04
 * 
 */


@WebServiceClient(name = "CopiaAutenticaWSServiceService", 
                  wsdlLocation = "file:/C:/Users/anadal.IBITNET/Desktop/SCAN_DIGITALITZACIO/Webservice/ServicioCopiaAutentica.wsdl",
                  targetNamespace = "http://service.ws.digital.caib.es/") 
public class CopiaAutenticaWSServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://service.ws.digital.caib.es/", "CopiaAutenticaWSServiceService");
    public final static QName CopiaAutenticaWSServicePort = new QName("http://service.ws.digital.caib.es/", "CopiaAutenticaWSServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/anadal.IBITNET/Desktop/SCAN_DIGITALITZACIO/Webservice/ServicioCopiaAutentica.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/C:/Users/anadal.IBITNET/Desktop/SCAN_DIGITALITZACIO/Webservice/ServicioCopiaAutentica.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public CopiaAutenticaWSServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CopiaAutenticaWSServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CopiaAutenticaWSServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns CopiaAutenticaWSService
     */
    @WebEndpoint(name = "CopiaAutenticaWSServicePort")
    public CopiaAutenticaWSService getCopiaAutenticaWSServicePort() {
        return super.getPort(CopiaAutenticaWSServicePort, CopiaAutenticaWSService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CopiaAutenticaWSService
     */
    @WebEndpoint(name = "CopiaAutenticaWSServicePort")
    public CopiaAutenticaWSService getCopiaAutenticaWSServicePort(WebServiceFeature... features) {
        return super.getPort(CopiaAutenticaWSServicePort, CopiaAutenticaWSService.class, features);
    }

}
