package es.caib.digital.ws.api.copiaautentica;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.12-patch-04
 * Wed Mar 09 13:26:15 CET 2016
 * Generated source version: 2.2.12-patch-04
 * 
 */
 
@WebService(targetNamespace = "http://service.ws.digital.caib.es/", name = "CopiaAutenticaWSService")
@XmlSeeAlso({ObjectFactory.class})
public interface CopiaAutenticaWSService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "generarCopiaTemporal", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.copiaautentica.GenerarCopiaTemporal")
    @WebMethod
    @ResponseWrapper(localName = "generarCopiaTemporalResponse", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.copiaautentica.GenerarCopiaTemporalResponse")
    public java.lang.String generarCopiaTemporal(
        @WebParam(name = "DocumentoElectronicoWS", targetNamespace = "")
        es.caib.digital.ws.api.copiaautentica.DocumentoElectronico documentoElectronicoWS
    );

    @WebResult(name = "DocumentoElectronicoWSResponse", targetNamespace = "")
    @RequestWrapper(localName = "generarCopiaAutentica", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.copiaautentica.GenerarCopiaAutentica")
    @WebMethod
    @ResponseWrapper(localName = "generarCopiaAutenticaResponse", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.copiaautentica.GenerarCopiaAutenticaResponse")
    public es.caib.digital.ws.api.copiaautentica.DocumentoElectronico generarCopiaAutentica(
        @WebParam(name = "DocumentoElectronicoWSParam", targetNamespace = "")
        es.caib.digital.ws.api.copiaautentica.DocumentoElectronico documentoElectronicoWSParam
    );

    @WebResult(name = "DocumentoElectronicoWSResponse", targetNamespace = "")
    @RequestWrapper(localName = "generarCopiaAutenticaDigitalizacion", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.copiaautentica.GenerarCopiaAutenticaDigitalizacion")
    @WebMethod
    @ResponseWrapper(localName = "generarCopiaAutenticaDigitalizacionResponse", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.copiaautentica.GenerarCopiaAutenticaDigitalizacionResponse")
    public es.caib.digital.ws.api.copiaautentica.DocumentoElectronico generarCopiaAutenticaDigitalizacion(
        @WebParam(name = "DocumentoElectronicoWSParam", targetNamespace = "")
        es.caib.digital.ws.api.copiaautentica.DocumentoElectronico documentoElectronicoWSParam
    );

    @WebResult(name = "DocumentoElectronicoWS", targetNamespace = "")
    @RequestWrapper(localName = "obtenerCopiaTemporal", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.copiaautentica.ObtenerCopiaTemporal")
    @WebMethod
    @ResponseWrapper(localName = "obtenerCopiaTemporalResponse", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.copiaautentica.ObtenerCopiaTemporalResponse")
    public es.caib.digital.ws.api.copiaautentica.DocumentoElectronico obtenerCopiaTemporal(
        @WebParam(name = "csv", targetNamespace = "")
        java.lang.String csv
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "generarCopiaCompulsaTemporal", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.copiaautentica.GenerarCopiaCompulsaTemporal")
    @WebMethod
    @ResponseWrapper(localName = "generarCopiaCompulsaTemporalResponse", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.copiaautentica.GenerarCopiaCompulsaTemporalResponse")
    public java.lang.String generarCopiaCompulsaTemporal(
        @WebParam(name = "DocumentoElectronicoWS", targetNamespace = "")
        es.caib.digital.ws.api.copiaautentica.DocumentoElectronico documentoElectronicoWS
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "generarCopiaSimpleTemporal", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.copiaautentica.GenerarCopiaSimpleTemporal")
    @WebMethod
    @ResponseWrapper(localName = "generarCopiaSimpleTemporalResponse", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.copiaautentica.GenerarCopiaSimpleTemporalResponse")
    public java.lang.String generarCopiaSimpleTemporal(
        @WebParam(name = "DocumentoElectronicoWS", targetNamespace = "")
        es.caib.digital.ws.api.copiaautentica.DocumentoElectronico documentoElectronicoWS
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "generarCopiaTemporalDigitalizacion", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.copiaautentica.GenerarCopiaTemporalDigitalizacion")
    @WebMethod
    @ResponseWrapper(localName = "generarCopiaTemporalDigitalizacionResponse", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.copiaautentica.GenerarCopiaTemporalDigitalizacionResponse")
    public java.lang.String generarCopiaTemporalDigitalizacion(
        @WebParam(name = "DocumentoElectronicoWS", targetNamespace = "")
        es.caib.digital.ws.api.copiaautentica.DocumentoElectronico documentoElectronicoWS
    );

    @WebResult(name = "DocumentoElectronicoWS", targetNamespace = "")
    @RequestWrapper(localName = "obtenerCopiaAutentica", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.copiaautentica.ObtenerCopiaAutentica")
    @WebMethod
    @ResponseWrapper(localName = "obtenerCopiaAutenticaResponse", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.copiaautentica.ObtenerCopiaAutenticaResponse")
    public es.caib.digital.ws.api.copiaautentica.DocumentoElectronico obtenerCopiaAutentica(
        @WebParam(name = "csv", targetNamespace = "")
        java.lang.String csv
    );

    @WebResult(name = "DocumentoElectronicoWS", targetNamespace = "")
    @RequestWrapper(localName = "conformarCopiaAutentica", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.copiaautentica.ConformarCopiaAutentica")
    @WebMethod
    @ResponseWrapper(localName = "conformarCopiaAutenticaResponse", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.copiaautentica.ConformarCopiaAutenticaResponse")
    public es.caib.digital.ws.api.copiaautentica.DocumentoElectronico conformarCopiaAutentica(
        @WebParam(name = "csv", targetNamespace = "")
        java.lang.String csv
    );
}
