package es.caib.digital.ws.api.caratulas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.12-patch-04
 * Wed Mar 09 13:26:19 CET 2016
 * Generated source version: 2.2.12-patch-04
 * 
 */
 
@WebService(targetNamespace = "http://service.ws.digital.caib.es/", name = "CaratulasWSService")
@XmlSeeAlso({ObjectFactory.class})
public interface CaratulasWSService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCaratula", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.caratulas.GetCaratula")
    @WebMethod
    @ResponseWrapper(localName = "getCaratulaResponse", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.caratulas.GetCaratulaResponse")
    public es.caib.digital.ws.api.caratulas.CaratulaReturnInfo getCaratula(
        @WebParam(name = "arg0", targetNamespace = "")
        es.caib.digital.ws.api.caratulas.CoverParams arg0
    );
}
