
/*
 * 
 */

package es.caib.digital.ws.api.entidades;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.12-patch-04
 * Wed Mar 09 13:26:17 CET 2016
 * Generated source version: 2.2.12-patch-04
 * 
 */


@WebServiceClient(name = "EntidadesWSServiceImplService", 
                  wsdlLocation = "file:/C:/Users/anadal.IBITNET/Desktop/SCAN_DIGITALITZACIO/Webservice/ServicioEntidades.wsdl",
                  targetNamespace = "http://impl.service.ws.digital.caib.es/") 
public class EntidadesWSServiceImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://impl.service.ws.digital.caib.es/", "EntidadesWSServiceImplService");
    public final static QName EntidadesWSServiceImplPort = new QName("http://impl.service.ws.digital.caib.es/", "EntidadesWSServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/anadal.IBITNET/Desktop/SCAN_DIGITALITZACIO/Webservice/ServicioEntidades.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/C:/Users/anadal.IBITNET/Desktop/SCAN_DIGITALITZACIO/Webservice/ServicioEntidades.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public EntidadesWSServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EntidadesWSServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EntidadesWSServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns EntidadesWSService
     */
    @WebEndpoint(name = "EntidadesWSServiceImplPort")
    public EntidadesWSService getEntidadesWSServiceImplPort() {
        return super.getPort(EntidadesWSServiceImplPort, EntidadesWSService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EntidadesWSService
     */
    @WebEndpoint(name = "EntidadesWSServiceImplPort")
    public EntidadesWSService getEntidadesWSServiceImplPort(WebServiceFeature... features) {
        return super.getPort(EntidadesWSServiceImplPort, EntidadesWSService.class, features);
    }

}
