package es.caib.digital.ws.api.entidades;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.12-patch-04
 * Wed Mar 09 13:26:17 CET 2016
 * Generated source version: 2.2.12-patch-04
 * 
 */
 
@WebService(targetNamespace = "http://service.ws.digital.caib.es/", name = "EntidadesWSService")
@XmlSeeAlso({ObjectFactory.class})
public interface EntidadesWSService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteLogoEntidad", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.entidades.DeleteLogoEntidad")
    @WebMethod
    @ResponseWrapper(localName = "deleteLogoEntidadResponse", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.entidades.DeleteLogoEntidadResponse")
    public es.caib.digital.ws.api.entidades.Entidad deleteLogoEntidad(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getEntidadDynamic", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.entidades.GetEntidadDynamic")
    @WebMethod
    @ResponseWrapper(localName = "getEntidadDynamicResponse", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.entidades.GetEntidadDynamicResponse")
    public java.util.List<es.caib.digital.ws.api.entidades.Entidad> getEntidadDynamic(
        @WebParam(name = "arg0", targetNamespace = "")
        es.caib.digital.ws.api.entidades.Entidad arg0
    );

    @RequestWrapper(localName = "deleteEntidad", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.entidades.DeleteEntidad")
    @WebMethod
    @ResponseWrapper(localName = "deleteEntidadResponse", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.entidades.DeleteEntidadResponse")
    public void deleteEntidad(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @RequestWrapper(localName = "deleteEntidadAll", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.entidades.DeleteEntidadAll")
    @WebMethod
    @ResponseWrapper(localName = "deleteEntidadAllResponse", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.entidades.DeleteEntidadAllResponse")
    public void deleteEntidadAll(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateEntidad", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.entidades.UpdateEntidad")
    @WebMethod
    @ResponseWrapper(localName = "updateEntidadResponse", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.entidades.UpdateEntidadResponse")
    public es.caib.digital.ws.api.entidades.Entidad updateEntidad(
        @WebParam(name = "arg0", targetNamespace = "")
        es.caib.digital.ws.api.entidades.Entidad arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updatePlantillaEntidad", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.entidades.UpdatePlantillaEntidad")
    @WebMethod
    @ResponseWrapper(localName = "updatePlantillaEntidadResponse", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.entidades.UpdatePlantillaEntidadResponse")
    public es.caib.digital.ws.api.entidades.Entidad updatePlantillaEntidad(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        byte[] arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveEntidad", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.entidades.SaveEntidad")
    @WebMethod
    @ResponseWrapper(localName = "saveEntidadResponse", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.entidades.SaveEntidadResponse")
    public es.caib.digital.ws.api.entidades.Entidad saveEntidad(
        @WebParam(name = "arg0", targetNamespace = "")
        es.caib.digital.ws.api.entidades.Entidad arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveEntidadAll", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.entidades.SaveEntidadAll")
    @WebMethod
    @ResponseWrapper(localName = "saveEntidadAllResponse", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.entidades.SaveEntidadAllResponse")
    public es.caib.digital.ws.api.entidades.Entidad saveEntidadAll(
        @WebParam(name = "arg0", targetNamespace = "")
        es.caib.digital.ws.api.entidades.Entidad arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTodasEntidades", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.entidades.GetTodasEntidades")
    @WebMethod
    @ResponseWrapper(localName = "getTodasEntidadesResponse", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.entidades.GetTodasEntidadesResponse")
    public java.util.List<es.caib.digital.ws.api.entidades.Entidad> getTodasEntidades();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deletePlantillaEntidad", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.entidades.DeletePlantillaEntidad")
    @WebMethod
    @ResponseWrapper(localName = "deletePlantillaEntidadResponse", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.entidades.DeletePlantillaEntidadResponse")
    public es.caib.digital.ws.api.entidades.Entidad deletePlantillaEntidad(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getEntidad", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.entidades.GetEntidad")
    @WebMethod
    @ResponseWrapper(localName = "getEntidadResponse", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.entidades.GetEntidadResponse")
    public es.caib.digital.ws.api.entidades.Entidad getEntidad(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateLogoEntidad", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.entidades.UpdateLogoEntidad")
    @WebMethod
    @ResponseWrapper(localName = "updateLogoEntidadResponse", targetNamespace = "http://service.ws.digital.caib.es/", className = "es.caib.digital.ws.api.entidades.UpdateLogoEntidadResponse")
    public es.caib.digital.ws.api.entidades.Entidad updateLogoEntidad(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        byte[] arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );
}
